apiVersion: v1
kind: Pod
metadata:
  name: gcp-k8s-pod
  labels:
    app: web
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: gcp-k8s-db-1
    image: gcp-k8s-db:v1
  - name: gcp-k8s-web-1
    image: gcp-k8s-web:v1
    volumeMounts:
    - name: shared-data
      mountPath: /api-cfg
  - name: gcp-k8s-api-1
    image: gcp-k8s-api:v1
    volumeMounts:
    - name: shared-data
      mountPath: /web-cfg
